name: 'Send Email via Gmail OAuth2'
description: 'A GitHub Action to send an email using Nodemailer and Gmail OAuth2'
author: 'David Smith'

inputs:
  from_email:
    description: 'Email address from which the email will be sent (optional, defaults to user email)'
    required: false
  to_email:
    description: 'Email address to which the email will be sent (optional, defaults to user email)'
    required: true
  subject:
    description: 'Subject of the email'
    required: true
  text:
    description: 'Body of the email'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run email script
      run: node ./scripts/send-email.js
      shell: bash
      env:
        GMAIL_CLIENT_ID: ${{ env.GMAIL_CLIENT_ID }}
        GMAIL_CLIENT_SECRET: ${{ env.GMAIL_CLIENT_SECRET }}
        GMAIL_REFRESH_TOKEN: ${{ env.GMAIL_REFRESH_TOKEN }}
        GMAIL_USER: ${{ env.GMAIL_USER }}
        FROM_EMAIL: ${{ inputs.from_email || env.GMAIL_USER }}
        TO_EMAIL: ${{ inputs.to_email || env.GMAIL_USER }}
        SUBJECT: ${{ inputs.subject }}
        TEXT: ${{ inputs.text }}