name: 'Send Email via Gmail OAuth2'
description: 'A GitHub Action to send an email using Gmail OAuth2'
author: 'David Smith'

inputs:
  from_email:
    description: 'Email address from which the email will be sent (optional, defaults to user email)'
    required: false
  to_email:
    description: 'Email address to which the email will be sent (optional, defaults to user email)'
    required: true
  subject:
    description: 'Subject of the email'
    required: true
  text:
    description: 'Body of the email'
    required: true

runs:
  using: 'node16'
  main: 'scripts/send-email.js'